# CONFIGURATION PARAMETERS
model_name: "chatbot_00"

val_test_ratio: [0.07, 0.07]
shuffle: True
seed: 123

# Model Hyperparams
learning_rate: 0.0005
n_epochs: 1
batch_size: 64
val_batch_size: 128

embedding_size: 200
encoder_lstm_units: 64
decoder_lstm_units: 64
output_activation: 'linear'

use_gpu: True

# minor param: delay in seconds (float) in final chat
chat_sleep_time: 0
