# CONFIGURATION PARAMETERS

model_name: "chatbot_00"
seed: 123


# Model Hyperparams
embedding_size: 200

encoder_lstm_units: 100
recurrent_initializer: "glorot_uniform"

conv_filters: [32, 32, 32, 32, 32]
kernel_size: 3
conv_activation: "elu"
use_batchnorm: True

decoder_lstm_units: 100
decoder_dense_units: 100
decoder_dense_activation: "elu"


# Training params
val_test_size: [0.05, 0.05]
n_epochs: 4
shuffle: True
batch_size: 64
learning_rate: 0.0005
