# CONFIGURATION PARAMETERS

# Paths
data_path: ""
save_path: ""


# Hyperparams
len_input:
dict_size: None

embedding_size: 300

encoder_lstm_units:
recurrent_initializer: "glorot_uniform"

conv_filters: [8, 16, 32]
kernel_size: 3
conv_activation: "elu"
use_batchnorm: True

decoder_lstm_units:
decoder_dense_units: 
decoder_dense_activation: "elu"
decoder_output_activation: "relu"


# Training params
n_epochs: 50
shuffle: True

batch_size: 64
learning_rate: 0.0001

