# CONFIGURATION PARAMETERS
model_name: "chatbot_00"

val_test_ratio: [0.07, 0.07]
shuffle: True
seed: 123

# Model Hyperparams
learning_rate: 0.0005
n_epochs: 4
batch_size: 64
val_batch_size: 128

embedding_size: 150
encoder_lstm_units: 64
decoder_lstm_units: 64

use_gpu: True
